language: node_js
node_js:
  - node
notifications:
  email: false
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: "Install & Build"
      script: npm install && npm run build
    - stage: "Deploy"
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: $PROD_FIREBASE_TOKEN
stages:
  - "Build"
  - name: "Deploy"
    if: branch = master